<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types=1);

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_layout_table_library_info_build(): array {
  $libraryVersionChecker = \Drupal::service('ckeditor5_plugin_pack.core_library_version_checker');
  if (!$libraryVersionChecker->isLibraryVersionHigherOrEqual('45.0.0')) {
    return [];
  }
  return ckeditor5_plugin_pack_library_loader(['layout-table']);
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_plugin_pack_layout_table_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  $libraryVersionChecker = \Drupal::service('ckeditor5_plugin_pack.core_library_version_checker');
  if (!$libraryVersionChecker->isLibraryVersionHigherOrEqual('45.0.0')) {
    unset($plugin_definitions['ckeditor5_plugin_pack_layout_table__layout_table']);
  }
}

/**
 * Implements hook_editor_js_settings_alter().
 */
function ckeditor5_plugin_pack_layout_table_editor_js_settings_alter(array &$settings) {
  // Ensure that the table contentToolbar items are unique.
  foreach ($settings["editor"]["formats"] as $format_id => $format) {
    if ($format['editor'] !== 'ckeditor5') {
      continue;
    }
    $editorConfig = $format["editorSettings"]["config"];
    if (isset($editorConfig["table"]['disableProperties'])) {

      if ($editorConfig["table"]['disableProperties']) {
        foreach ($editorConfig["table"]['contentToolbar'] as $key => $value) {
          if (in_array($value, ['tableProperties', 'tableCellProperties'])) {
            unset($editorConfig["table"]['contentToolbar'][$key]);
          }
        }
        $settings["editor"]["formats"][$format_id]["editorSettings"]["config"]["table"]['contentToolbar'] = array_values($editorConfig["table"]['contentToolbar']);
      }
      else {
        $settings["editor"]["formats"][$format_id]["editorSettings"]["config"]["table"]['contentToolbar'] = array_unique($editorConfig["table"]['contentToolbar']);
      }

    }
  }
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_layout_table_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_plugin_pack_layout_table_uninstall($is_syncing) {
  ckeditor5_plugin_pack_remove_ckeditor_plugins(['insertTableLayout', 'tableType'], [
    'ckeditor5_plugin_pack_layout_table__table_properties'
  ]);
}
