<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types = 1);

use Drupal\filter\FilterFormatInterface;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_restricted_editing_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['restricted-editing']);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_restricted_editing_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_plugin_pack_restricted_editing_uninstall($is_syncing): void {
  ckeditor5_plugin_pack_remove_ckeditor_plugins(['restrictedEditing']);
}

/**
 * Implements hook_editor_js_settings_alter().
 */
function ckeditor5_plugin_pack_restricted_editing_editor_js_settings_alter(array &$settings): void {
  foreach ($settings["editor"]["formats"] as $format_id => $format_settings) {
    if (!isset($format_settings['editor'])) {
      continue;
    }
    if ($format_settings['editor'] !== 'ckeditor5') {
      continue;
    }
    if (!isset($format_settings["editorSettings"]["config"]["restricted"])) {
      continue;
    }

    $id = array_search('restrictedEditing', $format_settings["editorSettings"]["toolbar"]["items"]);

    if ($format_settings["editorSettings"]["config"]["restricted"] === false) {
      $settings["editor"]["formats"][$format_id]["editorSettings"]["toolbar"]["items"][$id] = 'restrictedEditingException:auto';
    }
  }
}

/**
 * Implements hook_filter_format_disable().
 */
function ckeditor5_plugin_pack_restricted_editing_filter_format_disable(FilterFormatInterface $format) {
  // Revoke Restricted Editing permission after text format is disabled.
  /** @var \Drupal\ckeditor5_plugin_pack_restricted_editing\Utility\PermissionHelper $permissionHelper */
  $permissionHelper = \Drupal::service('ckeditor5_plugin_pack_restricted_editing.permission_helper');
  $permissionHelper->revokeRestrictedEditingPermission([$format]);
}
