<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types=1);

use Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition;

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_plugin_pack_font_library_info_build(): array {
  return ckeditor5_plugin_pack_library_loader(['font']);
}

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_font_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_plugin_pack_font_uninstall($is_syncing) {
  ckeditor5_plugin_pack_remove_ckeditor_plugins(['fontFamily', 'fontSize', 'fontColor', 'fontBackgroundColor'], [
    'ckeditor5_plugin_pack_font__font_color',
    'ckeditor5_plugin_pack_font__font_family',
    'ckeditor5_plugin_pack_font__font_size'
  ]);
}
