<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;
use Drupal\ckeditor5_premium_features_productivity_pack\Element\TextFormat;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\editor\EditorInterface;
use Drupal\text\Plugin\Field\FieldType\TextItemBase;

/**
 * Implements hook_uninstall().
 */
function ckeditor5_premium_features_productivity_pack_uninstall($is_syncing) {
  ckeditor5_premium_features_remove_ckeditor_plugins(['caseChange', 'tableOfContents', 'formatPainter', 'insertTemplate'],
  ['ckeditor5_premium_features_productivity_pack_base', 'ckeditor5_premium_features_productivity_pack_case_change']);
}

/**
 * Implements hook_element_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_element_info_alter(array &$info): void {
  if (isset($info['text_format'])) {
    $info['text_format']['#process'][] = [TextFormat::class, 'process'];
  }
}
/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_productivity_pack_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $libraries = [
    'format-painter',
    'document-outline',
    'template',
    'slash-command',
    'paste-from-office-enhanced',
    'case-change'
  ];

  $definitions = [];

  foreach ($libraries as $library) {
    $definition = new LibraryDefinitionItem($library, $config_handler->getDllLocation());
    $definition->addRemoteJs($definition->id());

    $definitions[$definition->id()] = $definition->getDefinition();
  }

  return $definitions;

}

/**
 * Implements hook_library_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_library_info_alter(&$libraries, $extension): void {
  // Do not load Paste from Office Enhanced if CKEditor version doesn't support it.
  if ($extension == 'ckeditor5_premium_features_productivity_pack') {
    if (!\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('39.0.0')) {
      unset($libraries["paste-from-office-enhanced"]);
    }
  }
}

/**
 * Implements hook_ckeditor5_plugin_info_alter().
 */
function ckeditor5_premium_features_productivity_pack_ckeditor5_plugin_info_alter(array &$plugin_definitions): void {
  // Do not load Paste from Office Enhanced if CKEditor version doesn't support it.
  if (!\Drupal::service('ckeditor5_premium_features.core_library_version_checker')->isLibraryVersionHigherOrEqual('39.0.0')) {
    unset($plugin_definitions["ckeditor5_premium_features_productivity_pack_paste_from_office_enhanced"]);
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor5_premium_features_productivity_pack_preprocess_field(&$variables) {
  $items = $variables['element']['#items'];
  if (!$items instanceof FieldItemListInterface) {
    return;
  }

  $editor_storage = \Drupal::entityTypeManager()->getStorage('editor');
  foreach ($items as $item) {
    if (!$item instanceof TextItemBase) {
      continue;
    }

    if (!isset($item->format)) {
      continue;
    }

    $editor = $editor_storage->load($item->format);
    if (!$editor instanceof EditorInterface) {
      continue;
    }

    if ($editor->getEditor() !== 'ckeditor5') {
      continue;
    }

    $settings = $editor->getSettings();
    if (in_array('tableOfContents', $settings['toolbar']['items'], TRUE)) {
      $variables['#attached']['library'][] = 'ckeditor5_premium_features_productivity_pack/table_of_contents.style';
    }
  }
}
