<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

/**
 * @file
 * Contains CKEditor 5 Premium Features Export to Word module functions.
 */

declare(strict_types = 1);

use Drupal\ckeditor5_premium_features\Utility\LibraryDefinitionItem;

/**
 * Implements hook_install().
 */
function ckeditor5_premium_features_export_word_install(): void {
  ckeditor5_premium_features_display_dependency_general_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_premium_features_export_word_uninstall($is_syncing) {
  ckeditor5_premium_features_remove_ckeditor_plugins(['exportWord'], ['ckeditor5_premium_features_export_word__export_word']);
}

/**
 * Implements hook_library_info_build().
 */
function ckeditor5_premium_features_export_word_library_info_build(): array {
  /** @var \Drupal\ckeditor5_premium_features\Config\SettingsConfigHandlerInterface $config_handler */
  $config_handler = \Drupal::service('ckeditor5_premium_features.config_handler.settings');

  $library = new LibraryDefinitionItem('export-word', $config_handler->getDllLocation());
  $library->addRemoteJs($library->id());
  $library->addDependency('ckeditor5_premium_features/cloud-services');

  $libraries[$library->id()] = $library->getDefinition();

  return $libraries;
}
