group_content_enabler.config.invitation_subject:
  type: 'text'
  label: 'Subject'

group_content_enabler.config.invitation_body:
  type: 'text'
  label: 'Body'

group_content_enabler.config.existing_user_invitation_subject:
  type: 'text'
  label: 'Subject'

group_content_enabler.config.existing_user_invitation_body:
  type: 'text'
  label: 'Body'

group_content_enabler.config.unblock_invitees:
  type: 'boolean'
  label: 'Unblock invitees'

group_content_enabler.config.invitation_bypass_form:
  type: 'boolean'
  label: 'Accept invitations immediately'
