<?php

/*
 * Copyright (c) 2003-2026, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function ckeditor5_plugin_pack_select_all_install($is_syncing): void {
  ckeditor5_plugin_pack_display_trial_info_message();
}

/**
 * Implements hook_uninstall().
 */
function ckeditor5_plugin_pack_select_all_uninstall($is_syncing) {
  ckeditor5_plugin_pack_remove_ckeditor_plugins(['selectAll']);
}
