
modules:
  basket:
    name: Drupal AlternativeCommerce (Basket)
    url: https://www.drupal.org/project/basket
    logo: basket.svg
  etherapi:
    name: EtherAPI
    url: https://www.drupal.org/project/etherapi
    logo: etherapi.png
  bitaps:
    name: Bitaps payment
    url: https://www.drupal.org/project/bitaps
    logo: bitaps.svg
  perfectmoney:
    name: Perfect Money
    url: https://www.drupal.org/project/perfectmoney
    logo: perfectmoney.png
  basket_paypal:
    name: AlternativeCommerce PayPal Checkout
    url: https://www.drupal.org/project/basket_paypal
    logo: basket_paypal.svg
  liqpay:
    name: Liqpay payment API
    url: https://www.drupal.org/project/liqpay
    logo: liqpay.png
  payeer:
    name: Payeer Electronic Wallet
    url: https://www.drupal.org/project/payeer
    logo: payeer.png
  basket_novaposhta:
    name: AlternativeCommerce NovaPoshta API
    url: https://www.drupal.org/project/basket_novaposhta
    logo: np.png
  novaposhta_tracking:
    name: NovaPoshta Tracking API
    url: https://www.drupal.org/project/novaposhta_tracking
    logo: np.png

videos:
  - https://www.youtube.com/embed/7K9J2xRL9kI

youtube:
  url: https://www.youtube.com/channel/UCQbytwao3Nyoi2OlIjT-OgQ
  name: AlternativeCommerce - free Drupal shop
