New:
  color: '#D87500'
  default: 1
  weight: 0
In processing:
  color: '#0569CC'
  weight: 1
To send:
  color: '#ffffff'
  weight: 2
Sent:
  color: '#ffffff'
  weight: 3
Delivered:
  color: '#ffffff'
  weight: 4
Not phoned:
  color: '#ffffff'
  weight: 5
Canceled:
  color: '#fa0505'
  weight: 6
Completed:
  color: '#00A337'
  weight: 7
Return:
  color: '#ff7e0d'
  weight: 8
Doubled:
  color: '#edc04e'
  weight: 9
