# NovaPoshta
novaposhta:
  ico: 'novaposhta.svg'
  name: 'NovaPoshta'
# Justin
justin:
  ico: 'justin.svg'
  neme: 'Justin'
# Meest Express
meest-express:
  ico: 'meest-express.svg'
  name: 'Meest Express'
# Укрпошта
ukrposhta:
  ico: 'ukrposhta.svg'
  name: 'Укрпошта'
# Автолюкс Експрес Пошта
autolux-post:
  ico: 'autolux_post.svg'
  name: 'Автолюкс Експрес Пошта'
