add:
  title: 'Add to cart'
  lists:
    basket_add:
      title: 'Hook the substitution of parameters included in the template button add'
      params: '&$info'
    basket_add_popup:
      title: 'Hook replace the parameters included in the template popup after adding'
      params: '&$info'
    basket_getItemPrice:
      title: 'Hook override the price of an item'
      params: '&$price, $row'
    basket_getItemPriceAfter:
      title: 'Processing the price after it has been determined'
      params: '&$price, $row'
    basket_getItemDiscount:
      title: 'Override position discount'
      params: '&$discount, $row'
    basket_getItemImg:
      title: 'Hook override the picture of the element'
      params: '&$fid, $row'
    basket_add_field_views_defineOptions:
      title: 'Overriding the default value of the fields in the add button'
      params: '&$options'
    basket_add_field_views_buildOptionsForm:
      title: 'Override field set in the add button'
      params: '&$form, $options'
    basket_getTotalSum:
      title: 'Hook override total order value'
      params: '&$totalSum, $items, $notDiscount = FALSE, $notDelivety = FALSE'
    basket_getPayInfo:
      title: 'Change data for payment'
      params: '&$payInfo'
    basket_current_currency:
      title: 'Change current user currency'
      params: '&$currency'
    basket_count_input_attr:
      title: 'Change attributes for count field'
      params: '&$attr, $entityID, $params = NULL'
    basket_getItemsInBasketQuery:
      title: 'Spoofing a request to receive a basket'
      params: '&$query'

params:
  title: 'Params'
  lists:
    basket_params_definition:
      title: 'Alter parameter definition'
      params: '&$element, $params, $isInline'
    basketValidParams:
      title: 'Validation of add to cart'
      params: '&$response, &$isValid, $post'

order:
  title: 'Checkout'
  lists:
    basket_order_tokenDefaultValue:
      title: 'Hook replace default order values when creating'
      params: '&$node'
    basket_insertOrder:
      title: 'Hook for data retention to save when ordering'
      params: '&$basketOrderFields, &$basketItems, $entity'
    basket_postInsertOrder:
      title: 'Hook after ordering. Transmitted node and order ID'
      params: '$entity, $orderId'
    basket_ajaxReloadDelivery:
      title: 'Ajax return hook'
      params: '&$response'
    basket_delivery_preInit:
      title: 'Change of form before initialization of delivery'
      params: '&$form, &$form_state'
    basket_ajaxReloadPayment:
      title: 'Ajax return hook'
      params: '&$response'
    basket_payment_option_access:
      title: 'Change the availability of a payment point'
      params: '&$access, $paymentKey, $form_state'
    basket_delivery_option_access:
      title: 'Change the availability of a delivery point'
      params: '&$access, $deliveryKey, $form_state'
    basketPaymentField:
      title: 'Hook adding sub payment fields'
      params: '&$form, $form_state'
    basket_order_get_id:
      title: 'Hook the order number format'
      params: '&$orderID'
    basket_submit_ajax_response:
      title: 'Change response after successful submission'
      params: '&$response, $form, $form_state'

node_type:
  title: 'Material type'
  lists:
    basket_node_type_extra_fields_form:
      title: 'Hook control additional fields types of materials'
      params: '&$form, $form_state'
    basket_node_type_extra_fields_list:
      title: 'Hook output data on additional fields of material'
      params: '&$field, $setting, $key'
    basketNodeGetPriceField:
      title: 'Hook of redefinition of the request for determining the price of goods'
      params: '&$queryPrice, $nodeTypes = [], $nid = NULL'
      descriptions: ['', Return fields:', '- nid','- price','- currency','- priceConvert','- priceConvertOld']
    stockProductLinks:
      title: 'Hook for changing the list of actions with a product'
      params: '&$links, $entity'

admin_pages:
  title: 'Admin page'
  lists:
    basket_admin_page:
      title: 'Hook override the pages of the admin box of the basket'
      params: '&$element, $params'
    basket_get_new_count:
      title: 'Redefinition of the amount of new data in the admin panel'
      params: '&$count, $type'
    basket_order_links:
      title: 'List of order management links'
      params: '&$links, $order'
    basketOrderUpdate:
      title: 'Hook triggered after updating the basket'
      params: '&$updateOrder, $orderOld'
    basketTemplateTokens:
      title: 'Hook basket template tokens'
      params: '&$tokens, $templateKey'
    basketTokenValue:
      title: 'Hook basket token value'
      params: '&$value, $tokenName, $params'
    payment_settings_info:
      title: 'Substitution of information about the settings of the payment point'
      params: '&$items, $result'
    delivery_settings_info:
      title: 'Substitution of information about the settings of the delivery point'
      params: '&$items, $result'
    basket_item:
      title: 'Hook for changing the state of an item in an order'
      params: '$item, $type'
      is_hook: true

user_pages:
  title: 'Public pages'
  lists:
    basket_pages:
      title: 'Hook basket page overrides'
      params: '&$element, $page_type, $page_subtype'

translate:
  title: 'Text settings'
  lists:
    basket_translate_context:
      title: 'The hook of adding texts from the rest of the modules to the basket text management system'
      params: '&$context'

access:
  title: 'Basket access'
  lists:
    basket_access:
      title: 'Access alter'
      params: '&$access, $permission, $options'
