# LiqPay
liqpay:
  ico: 'liqpay.svg'
  name: 'LiqPay'
# Portmone
portmone:
  ico: 'portmone.svg'
  name: 'Portmone'
# PayPal
paypal:
  ico: 'paypal.svg'
  name: 'PayPal'
# Skrill
skrill:
  ico: 'skrill.svg'
  name: 'Skrill'
# Wayforpay
wayforpay:
  ico: 'wayforpay.svg'
  name: 'Wayforpay'
# OnePay
onepay:
  ico: 'onepay.svg'
  name: 'OnePay'
#Ipay
ipay:
  ico: 'ipay.svg'
  name: 'iPay.ua'
#chast.monobank.ua
chast_monobank:
  ico: 'chast_monobank.svg'
  name: 'Payment in parts'
#Fondy
fondy:
  ico: 'fondy.svg'
  name: 'Fondy'
#Cashback
Cashback:
  ico: 'cashback.svg'
  name: 'Cashback'
#TronAPI
tron_api:
  ico: 'tron_api.svg'
  name: 'TRON API'
#EtherAPI
EtherAPI:
  ico: 'EtherAPI.svg'
  name: 'Ether API'
#PerfectMoney
PerfectMoney:
  ico: 'PerfectMoney.svg'
  name: 'Perfect Money'