# Pages
page:
  title: 'Pages'
  templates:
    # Successful order page template
    basket_finish:
      title: 'Successful order page template'
      language: true
      text_format: true
      twig_template: 'basket-page-finish.html.twig'
# Emails
mail:
  title: 'Emails'
  templates:
    # Admin notification of new order
    notification_order_admin:
      title: 'Admin notification of new order'
      language: true
      text_format: true
      twig_template: 'notification-order-admin.html.twig'
      token: TRUE
      preview: TRUE
      subject: TRUE
      token_twig:
        'order_num': 'Order number'
        'order_count': 'Order count'
        'order_edit_link': 'Edit order link'
        'order_list': 'Order list'
        'order_fields': 'Order fields'
        'order_status': 'Order status'
        'order_status_color': 'Order status (color)'
        'order_fin_status': 'Financial status'
        'order_fin_status_color': 'Financial status (color)'
    # Notification to the user about the created order
    notification_order_user:
      title: 'Notification to the user about the created order'
      language: true
      text_format: true
      token: TRUE
      preview: TRUE
      subject: TRUE
      twig_template: 'notification-order-user.html.twig'
      token_twig:
        'order_num': 'Order number'
        'order_count': 'Order count'
        'order_list': 'Order list'
        'order_status': 'Order status'
        'order_status_color': 'Order status (color)'
        'order_fin_status': 'Financial status'
        'order_fin_status_color': 'Financial status (color)'
        'order_fields': 'Order fields'
    # General letter template
    notification_html:
      title: 'General letter template'
      inline_twig: TRUE
      token: TRUE
      preview: TRUE
      token_twig: 
        'logo': 'Logo'
        'content': 'Content'
        'theme_path': 'Theme path'
        'basket_imgs': 'Basket path imgs'
        'appearance_color': 'Background color'
        'appearance_color_text': 'Text color'
        'phone_html': 'Phone HTML'
        'work_html': 'Schedule of work HTML'
        'soc_links': 'Social links'
    # Order list
    order_table:
      title: 'Order list'
      inline_twig: TRUE
      token: TRUE
      token_twig:
        'order_list': 'Order list'
    # Order fields
    order_fields:
      title: 'Order fields'
      inline_twig: TRUE
      token: TRUE
      token_twig:
        'node': 'Order'
        'build': 'Order fields'
        'order': 'Order data'
# Orders
order:
  title: 'Orders'
  templates:
    # Order information block
    order_info:
      title: 'Order information block'
      inline_twig: TRUE
      token: TRUE
      token_twig:
        'node': 'Order'
        'build': 'Order fields'
        'order': 'Order data'
        'order_status': 'Order status'
        'order_status_color': 'Order status (color)'
        'order_status_select': 'Order status (select)'
        'order_fin_status': 'Financial status'
        'order_fin_status_color': 'Financial status (color)'
        'order_fin_status_select': 'Financial status (select)'
    # Order data
    order_view_info:
      title: 'Order data'
      inline_twig: TRUE
      token: TRUE
      token_twig:
        'node': 'Order'
        'build': 'Order fields'
        'order': 'Order data'
        'order_status': 'Order status'
        'order_fin_status': 'Financial status'
# Waybill
waybill:
  title: 'Waybill'
  templates:
    # Waybill template header
    waybill_header:
      title: 'Waybill template header'
      inline_twig: TRUE
      token: TRUE
      token_twig:
        'node': 'Order'
        'order_num': 'Order number'
        'build': 'Order fields'
        'order': 'Order data'
        'order_status': 'Order status'
        'logo': 'Logo'
        'content': 'Content'
        'theme_path': 'Theme path'
    # Waybill template
    waybill:
      title: 'Waybill template'
      inline_twig: TRUE
      token: TRUE
      twig_template: 'basket-waybill.html.twig'
      token_twig:
        'node': 'Order'
        'order_num': 'Order number'
        'build': 'Order fields'
        'order': 'Order data'
        'order_status': 'Order status'
        'order_fin_status': 'Financial status'
