order_num: 'Order number'
node: 'Order'
build: 'Order fields'
order: 'Order data'
order_status: 'Order status'
order_fin_status: 'Financial status'
item_title:
  title: 'Product name'
  lineAll: true
item_price:
  title: 'Product price'
  lineAll: true
item_count:
  title: 'Product count'
  lineAll: true
item_percent:
  title: 'Individual product discount.'
  lineAll: true
item_sum:
  title: 'Sum of goods with discount'
  lineAll: true
item_currency:
  title: 'Currency'
  lineAll: true
